[project]
site_name = "VSD - Video Stream Downloader"
site_description = "Documentation for vsd (video stream downloader)"
site_author = "clitic"
site_url = "https://clitic.github.io/vsd"
copyright = "Copyright &copy; 2026 clitic"
repo_url = "https://github.com/clitic/vsd"
nav = [
    { "Home" = "home.md" },
    { "Install" = "install.md" },
    { "Usage" = "usage.md" },
    { "Cli" = "cli.md" },
    { "Android" = "android.md" },
    { "Build" = "build.md" },
    { "Alternatives" = "alternatives.md" },
    { "Changelog" = "CHANGELOG.md", icon = "lucide/square-pen" },
]

[project.theme]
# variant = "classic"
# favicon = "images/favicon.png"
language = "en"
features = [
    "announce.dismiss",
    "content.action.edit",
    "content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    # "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
logo = "lucide/terminal"
repo = "fontawesome/brands/github"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/clitic/vsd"
